name: cancellation
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Max Anurin <maxim.anurin@zxteam.org>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.8
  pedantic: ^1.8.0
  test: ^1.6.0
